//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GgLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GgLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.GgLocalization", typeof(GgLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить раздел.
        /// </summary>
        public static string AddChapter {
            get {
                return ResourceManager.GetString("AddChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все элементы совпадают!.
        /// </summary>
        public static string AllElementsMatch {
            get {
                return ResourceManager.GetString("AllElementsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уверены что хотите уйти?.
        /// </summary>
        public static string AreYouSureToExit {
            get {
                return ResourceManager.GetString("AreYouSureToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задания.
        /// </summary>
        public static string AssignmentsPage {
            get {
                return ResourceManager.GetString("AssignmentsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудио.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор файла с аудиозаписью.
        /// </summary>
        public static string AudioFileChoose {
            get {
                return ResourceManager.GetString("AudioFileChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудио файлы (.mp3, .wav, .aac) | *.mp3; *.wav; *.aac.
        /// </summary>
        public static string AudioFiles {
            get {
                return ResourceManager.GetString("AudioFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна новая версия {0}, обновить? Это может занять несколько минут.
        /// </summary>
        public static string AvailableNewVersion {
            get {
                return ResourceManager.GetString("AvailableNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фоновое изображение.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Построение.
        /// </summary>
        public static string BuildingTaskName {
            get {
                return ResourceManager.GetString("BuildingTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постройте предложение из данных слов.
        /// </summary>
        public static string BuildingTaskText {
            get {
                return ResourceManager.GetString("BuildingTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ура!.
        /// </summary>
        public static string Celebrating {
            get {
                return ResourceManager.GetString("Celebrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздел.
        /// </summary>
        public static string Chapter {
            get {
                return ResourceManager.GetString("Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название раздела.
        /// </summary>
        public static string ChapterTitle {
            get {
                return ResourceManager.GetString("ChapterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите раздел с которым хотите работать.
        /// </summary>
        public static string ChoosingChapterToWork {
            get {
                return ResourceManager.GetString("ChoosingChapterToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите удаление раздела {0}.
        /// </summary>
        public static string ConfirmingDelete {
            get {
                return ResourceManager.GetString("ConfirmingDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правильно.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База Данных.
        /// </summary>
        public static string DataBase {
            get {
                return ResourceManager.GetString("DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания: .
        /// </summary>
        public static string DateOfCreation {
            get {
                return ResourceManager.GetString("DateOfCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор файла баз данных.
        /// </summary>
        public static string DBFileChoose {
            get {
                return ResourceManager.GetString("DBFileChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы Баз Данных (.sgb) | *.sgb;.
        /// </summary>
        public static string DBFiles {
            get {
                return ResourceManager.GetString("DBFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание: .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элементы не совпадают!.
        /// </summary>
        public static string ElementsDoNotMatch {
            get {
                return ResourceManager.GetString("ElementsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать хотя бы одно слово для пропуска.
        /// </summary>
        public static string ExceptionMinWords {
            get {
                return ResourceManager.GetString("ExceptionMinWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильное форматирование.
        /// </summary>
        public static string ExceptionUncorrectFormate {
            get {
                return ResourceManager.GetString("ExceptionUncorrectFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к файлу:.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как { она | он } поживает? Как {погода}?.
        /// </summary>
        public static string FillingQuestion {
            get {
                return ResourceManager.GetString("FillingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнение.
        /// </summary>
        public static string FillingTaskName {
            get {
                return ResourceManager.GetString("FillingTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните пробелы.
        /// </summary>
        public static string FillingTaskText {
            get {
                return ResourceManager.GetString("FillingTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор файла с изображением.
        /// </summary>
        public static string ImageFileChoose {
            get {
                return ResourceManager.GetString("ImageFileChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы изображений | *.png; *.jpg; *.jpeg; *.tiff.
        /// </summary>
        public static string ImageFiles {
            get {
                return ResourceManager.GetString("ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно.
        /// </summary>
        public static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный ответ(ы).
        /// </summary>
        public static string IncorrectAnswer {
            get {
                return ResourceManager.GetString("IncorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установлена последняя версия!.
        /// </summary>
        public static string LastVersionInstalled {
            get {
                return ResourceManager.GetString("LastVersionInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудирование.
        /// </summary>
        public static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопоставление.
        /// </summary>
        public static string MatchingTaskName {
            get {
                return ResourceManager.GetString("MatchingTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите изображения и пропишите их описания.
        /// </summary>
        public static string MatchingTaskText {
            get {
                return ResourceManager.GetString("MatchingTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Материалы.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите все необходимые данные для материала.
        /// </summary>
        public static string NecessaryInfoForContent {
            get {
                return ResourceManager.GetString("NecessaryInfoForContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый Раздел.
        /// </summary>
        public static string NewChapter {
            get {
                return ResourceManager.GetString("NewChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть Базу Данных.
        /// </summary>
        public static string OpenDB {
            get {
                return ResourceManager.GetString("OpenDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откройте или создайте Базу Данных.
        /// </summary>
        public static string OpenOrCreateDB {
            get {
                return ResourceManager.GetString("OpenOrCreateDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия программы: .
        /// </summary>
        public static string ProgramVersion {
            get {
                return ResourceManager.GetString("ProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор файла с текстом.
        /// </summary>
        public static string RtfFileChoose {
            get {
                return ResourceManager.GetString("RtfFileChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы с RTF текстом (.rtf) | *.rtf;.
        /// </summary>
        public static string RtfFiles {
            get {
                return ResourceManager.GetString("RtfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздел.
        /// </summary>
        public static string SegmentPage {
            get {
                return ResourceManager.GetString("SegmentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор.
        /// </summary>
        public static string SelectingTaskName {
            get {
                return ResourceManager.GetString("SelectingTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите правильную пословицу.
        /// </summary>
        public static string SelectingTaskText {
            get {
                return ResourceManager.GetString("SelectingTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите описание.
        /// </summary>
        public static string SetDescription {
            get {
                return ResourceManager.GetString("SetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст изображения.
        /// </summary>
        public static string SetImageDescription {
            get {
                return ResourceManager.GetString("SetImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите изображение.
        /// </summary>
        public static string SetMatchingImage {
            get {
                return ResourceManager.GetString("SetMatchingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название материала.
        /// </summary>
        public static string SetMaterialTitle {
            get {
                return ResourceManager.GetString("SetMaterialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите название материала, выберите текст и аудио.
        /// </summary>
        public static string SetTitleAndDataForListeningMaterial {
            get {
                return ResourceManager.GetString("SetTitleAndDataForListeningMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест.
        /// </summary>
        public static string TestTaskName {
            get {
                return ResourceManager.GetString("TestTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пройдите тест.
        /// </summary>
        public static string TestTaskText {
            get {
                return ResourceManager.GetString("TestTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название: .
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
